name: streamlit
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - altair=5.5.0=pyhd8ed1ab_1
  - anyio=4.11.0=pyhcf101f3_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py312h4409184_1
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - aws-c-auth=0.9.1=h41ebd0a_3
  - aws-c-cal=0.9.2=hd08b81e_1
  - aws-c-common=0.12.4=h6caf38d_0
  - aws-c-compression=0.3.1=habbe1e8_6
  - aws-c-event-stream=0.5.6=hf65d68d_3
  - aws-c-http=0.10.4=h70a9c10_3
  - aws-c-io=0.22.0=h89d1e94_1
  - aws-c-mqtt=0.13.3=he7b126b_6
  - aws-c-s3=0.8.6=h7a3c519_5
  - aws-c-sdkutils=0.2.4=habbe1e8_1
  - aws-checksums=0.2.7=habbe1e8_2
  - aws-crt-cpp=0.34.4=h01415d0_0
  - aws-sdk-cpp=1.11.606=h2169b1b_4
  - azure-core-cpp=1.16.0=h88fedcc_1
  - azure-identity-cpp=1.12.0=hd83eed2_0
  - azure-storage-blobs-cpp=12.14.0=he094cc7_1
  - azure-storage-common-cpp=12.10.0=h2155cda_3
  - azure-storage-files-datalake-cpp=12.12.0=h30213e0_3
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - brotli-python=1.1.0=py312h6b01ec3_4
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=6.2.0=pyhd8ed1ab_0
  - cairo=1.18.4=h6a3b0d2_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py312hb65edc0_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312ha0dd364_2
  - cpython=3.12.11=py312hd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - debugpy=1.8.17=py312h56d30c9_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.0=py312h5748b74_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=hce30654_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - gflags=2.2.2=hf9b8971_1005
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - glog=0.7.1=heb240a5_0
  - greenlet=3.2.4=py312h6b01ec3_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh92f572d_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_genutils=0.2.0=pyhd8ed1ab_2
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py312h81bd7bf_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.9=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=1.1.11=pyhd8ed1ab_0
  - kiwisolver=1.4.9=py312hdc12c9d_1
  - krb5=1.21.3=h237132a_0
  - lark=1.3.0=pyhd8ed1ab_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libarrow=21.0.0=h4c37d73_6_cpu
  - libarrow-acero=21.0.0=hc317990_6_cpu
  - libarrow-compute=21.0.0=h75845d1_6_cpu
  - libarrow-dataset=21.0.0=hc317990_6_cpu
  - libarrow-substrait=21.0.0=h144af7f_6_cpu
  - libblas=3.9.0=36_h51639a9_openblas
  - libboost=1.86.0=hf493ff8_4
  - libboost-python=1.86.0=py312habbcb05_4
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.9.0=36_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.14.1=h73640d1_0
  - libcxx=21.1.2=hf598326_0
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.1.0=hfdf1602_1
  - libgfortran5=15.1.0=hb74de2c_1
  - libglib=2.86.0=h1bb475b_0
  - libgoogle-cloud=2.39.0=head0a95_0
  - libgoogle-cloud-storage=2.39.0=hfa3a374_0
  - libgrpc=1.73.1=hcdac78c_0
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=36_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libnghttp2=1.67.0=hc438710_0
  - libntlm=1.8=h5505292_0
  - libopenblas=0.3.30=openmp_h60d53f8_2
  - libopentelemetry-cpp=1.21.0=he15edb5_1
  - libopentelemetry-cpp-headers=1.21.0=hce30654_1
  - libparquet=21.0.0=h45c8936_6_cpu
  - libpng=1.6.50=h280e0eb_1
  - libpq=17.6=h31f7a3a_2
  - libprotobuf=6.31.1=h702a38d_1
  - librdkit=2025.03.6=hafd8b29_0
  - libre2-11=2025.08.12=h91c62da_1
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.50.4=h4237e3c_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.1=h7dc4979_0
  - libutf8proc=2.11.0=hc25f550_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.0=h9329255_1
  - libxml2-16=2.15.0=h0ff4647_1
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.0=hbb9b287_0
  - lz4-c=1.10.0=h286801f_1
  - matplotlib-base=3.10.6=py312h605b88b_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.4=pyhcf101f3_0
  - mols2grid=2.0.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.6.0=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.12.0=h248ca61_1
  - notebook=7.4.7=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - openjpeg=2.5.4=hbfb3c88_0
  - openldap=2.6.10=hbe55e7a_0
  - openssl=3.5.4=h5503f6c_0
  - orc=2.2.0=hca0cb2d_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.46=h7125dd6_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h81086ad_1
  - platformdirs=4.4.0=pyhcf101f3_0
  - plotly=6.4.0=pyhd8ed1ab_0
  - prometheus-cpp=1.3.0=h0967b3e_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - protobuf=6.31.1=py312h21839cc_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pubchempy=1.0.5=pyhd8ed1ab_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py3dmol=2.5.3=pyhd8ed1ab_0
  - pyarrow=21.0.0=py312h1f38498_0
  - pyarrow-core=21.0.0=py312h3dbcb64_0_cpu
  - pycairo=1.28.0=py312h0012f17_1
  - pycparser=2.22=pyh29332c3_1
  - pydeck=0.9.1=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyobjc-core=11.1=py312h4c66426_1
  - pyobjc-framework-cocoa=11.1=py312h3964663_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.11=hc22306f_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.12.11=hd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pyzmq=27.1.0=py312hd65ceae_0
  - qhull=2020.2=h420ef59_5
  - re2=2025.08.12=h64b956e_1
  - readline=8.2=h1d1bf99_2
  - referencing=0.36.2=pyh29332c3_0
  - reportlab=4.4.4=py312h4409184_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rlpycairo=0.4.0=pyh6c17108_0
  - rpds-py=0.27.1=py312h6f58b40_1
  - send2trash=1.8.3=pyh31c8845_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=hd121638_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - sqlalchemy=2.0.43=py312h163523d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py312ha11c99a_1
  - streamlit=1.50.0=pyhd8ed1ab_0
  - streamlit_option_menu=0.4.0=pyhd8ed1ab_1
  - tenacity=9.1.2=pyhd8ed1ab_0
  - terminado=0.18.1=pyh31c8845_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h892fb3f_2
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhe01879c_2
  - tornado=6.5.2=py312h163523d_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250822=pyhd8ed1ab_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - unicodedata2=16.0.0=py312h163523d_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - watchdog=6.0.0=py312h163523d_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - yaml=0.2.5=h925e9cb_3
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zstandard=0.25.0=py312h37e1c23_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - admetica==1.4.1
      - aimsim-core==2.2.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - astartes==1.2.2
      - attrs==23.2.0
      - blinker==1.8.2
      - chemprop==2.0.0
      - click==8.1.7
      - configargparse==1.7
      - dataclasses==0.6
      - deprecation==2.1.0
      - dill==0.3.8
      - filelock==3.15.4
      - flask==3.0.3
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - idna==3.7
      - ipyspeck==0.6.1
      - ipywidgets==7.6.3
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - jupyter-packaging==0.12.3
      - lightning==2.3.3
      - lightning-utilities==0.11.6
      - markupsafe==2.1.5
      - mhfp==1.9.6
      - mordredcommunity==2.0.6
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.3
      - numpy==1.26.4
      - packaging==24.1
      - padelpy==0.1.16
      - pandas==2.2.2
      - pillow==10.4.0
      - psutil==6.0.0
      - pystow==0.7.9
      - pytorch-lightning==2.3.3
      - pytz==2024.1
      - pyyaml==6.0.1
      - rdkit==2024.3.3
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - seaborn==0.13.2
      - setuptools==72.1.0
      - six==1.16.0
      - st-pages==1.0.1
      - stmol==0.0.9
      - streamlit-ketcher==0.0.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - threadpoolctl==3.5.0
      - tomlkit==0.13.3
      - torch==2.4.0
      - torchmetrics==1.4.0.post0
      - tqdm==4.66.4
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - useful-rdkit-utils==0.91
      - werkzeug==3.0.3
      - widgetsnbextension==3.5.2
      - yarl==1.9.4
prefix: /Users/ganeshshahane/miniconda3/envs/streamlit
